# Generated by Django 6.0.3 on 2026-05-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentbrief',
            name='service',
            field=models.CharField(choices=[('software', 'Software & Mobile App Engineering'), ('automation', 'AI Solutions & Business Automation'), ('cloud', 'Cloud Deployment & Infrastructure'), ('consulting', 'Strategic IT Consultancy'), ('other', 'Comprehensive Ecosystem Overhaul'), ('portfolio', 'Portfolio Creation, Review & Optimization'), ('other', 'Other - Please Specify in Message')], max_length=50),
        ),
    ]
